/**
 * Development client build orchestration with watch mode and live reload.
 *
 * Dev mode aligns with production behavior: `splitting: true` and hashed
 * filenames via `entryNames: "[dir]/[name].[hash]"`. Applications access
 * built assets through stable virtual URLs rather than hardcoded paths:
 *
 * - `GET /@entry/<entry>` - redirects to the current JS for that entry
 * - `GET /@style/<entry>` - redirects to the current CSS for that entry (if any)
 * - `GET /@manifest` - serves the manifest JSON (when manifest generation is enabled)
 *
 * The HTML live reload script is injected at request time for HTML responses.
 * If the HTML contains `</body>`, the script is injected before it; otherwise
 * it is appended to the document.
 *
 * Note: HTML files must exist in `outdir` before starting the dev server.
 * Any HTML not generated by the build should be copied there beforehand.
 *
 * @module
 *
 * @example
 * ```typescript
 * import { devClient } from "@ggpwnkthx/csr-dev";
 *
 * const dev = await devClient({
 *   entryPoints: ["src/client.ts"],
 *   outdir: ".dev",
 *   port: 35729,
 *   manifest: true,
 * });
 *
 * console.log(`Dev server running on http://localhost:${dev.port}`);
 * console.log(`Output directory: ${dev.outdir}`);
 * console.log(`Manifest: ${dev.manifestPath}`);
 *
 * await dev.stop();
 * ```
 */

export { DevServerError } from "@ggpwnkthx/csr-shared";

export { FileTooLargeError } from "./errors.ts";

export { devClient } from "./client.ts";
export { safeFilePath } from "./path-utils.ts";
export type { DevClientOptions, DevResult } from "./types.ts";
