/**
 * Development client build orchestration with watch mode and live reload.
 *
 * Dev mode aligns with production behavior: `splitting: true` and hashed
 * filenames via `entryNames: "[dir]/[name].[hash]"`. Applications access
 * built assets through stable virtual URLs rather than hardcoded paths:
 *
 * - `GET /@entry/<entry>` - redirects to the current JS for that entry
 * - `GET /@style/<entry>` - redirects to the current CSS for that entry (if any)
 *
 * The HTML live reload script is injected at request time for HTML responses.
 * If the HTML contains `</body>`, the script is injected before it; otherwise
 * it is appended to the document.
 *
 * Note: HTML files must exist in `outdir` before starting the dev server.
 * Any HTML not generated by the build should be copied there beforehand.
 *
 * @module
 */

export { DevServerError } from "@ggpwnkthx/csr-shared";

export { FileTooLargeError } from "./errors.ts";

export { devClient } from "./client.ts";
export { safeFilePath } from "./path-utils.ts";
export type { DevClientOptions, DevHandle } from "./types.ts";
