name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish-shared:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
        working-directory: packages/shared

  publish-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: publish-shared
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
        working-directory: packages/manifest

  publish-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: publish-manifest
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
        working-directory: packages/build

  publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: publish-build
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
        working-directory: packages/dev

  publish-root:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: publish-dev
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
        working-directory: .
